port: /dev/ttyUSB0
baud: 57600
timeout: 0.5
rate: 50
base_frame: base_link
#Thrusters pins
left_thruster_pin: 0
right_thruster_pin: 1
#Thrusters controller
rising_rate: 0.1
falling_rate: 1
setpoint_limit: 0.8
