1: "safety/recovery_action"
2: "control/disable_thrusters"
3: "control/enable_thrusters"
4: "control/disable_trajectory"
5: "topic_logger_robot/start_recording"
6: "topic_logger_robot/stop_recording"
7: "lights_on"
8: "lights_off"
9: "laser_on"
10: "laser_off"
11: "sonar_on"
12: "sonar_off"
