# Param file for the evologics driver, GS side
evologics:
    address: '192.168.1.245:9200'
    ownid: 1
    destid: 2
    power: 3 #1
    physical_interface_timeout: 0.1
    response_timeout: 1 #10.0
    modem_pos_timeout: 0.2 #1.0
    loop_period: 0.02
