master_sync/ignore_nodes: [/rosout,
                           "/*master_sync* node",
                           "remote /*master_discovery* node",
                           "/*node_manager", /*zeroconf, /robot_state_publisher_gs,
                           /robot_state_publisher_robot]

master_sync/sync_topics: [/navigation/nav_sts,
                          /xiroi/navigation/nav_sts,
                          /xiroi/joy]

master_sync/sync_services: [/xiroi/control/abort_mission,
                            /xiroi/control/enable_keep_position,
                            /xiroi/control/disable_keep_position,
                            /xiroi/control/enable_teleoperation,
                            /xiroi/control/disable_teleoperation]