master_sync/ignore_nodes: [/rosout,
                           "/*master_sync* node",
                           "remote /*master_discovery* node",
                           "/*node_manager", /*zeroconf, /robot_state_publisher_gs,
                           /robot_state_publisher_robot]
master_sync/sync_topics: [/control/thrusters_data,
                          /safety/emus_bms,
                          /safety/computer_logger,
                          /sensors/gps_raw,
                          /sensors/gps_robot_raw,
                          /sensors/gps_buoy_emlid_raw,
                          /sensors/gps_buoy_emlid_ned,
                          /sensors/gps_buoy_emlid_filtered,
                          /sensors/gps_buoy_emlid_diagnostics,
                          /sensors/gps_buoy_fastrax_raw,
                          /sensors/buoy_ned,
                          /sensors/modem_raw,
                          /sensors/modem_delayed,
                          /sensors/usbllong,
                          /sensors/usblangles,
                          /ekf_map/odometry,
                          /navigation/nav_sts,
                          /stereo_down/scaled_x2/left/image_rect_color,
                          /stereo_down/scaled_x2/left/camera_info,
                          /stereo_forward/scaled_x2/left/image_rect_color,
                          /stereo_forward/scaled_x2/left/camera_info,
                          /stereo_down_sync/info,
                          /control/map_ack_ack,
                          /control/map_ack_data,
                          /control/map_ack_ok,
                          /control/body_velocity_req,
                          /control/merged_body_velocity_req,
                          /control/secure_body_velocity_req,
                          /sensors/min_diagnostics,
                          /joint_states,
                          /joy,
                          /keyboard,
                          /usbl/im/in,
                          /usbl/im/out,
                          /modem/im/in,
                          /modem/im/out,
                          /move_base/global_costmap/costmap,
                          /minoru/left/image_rect_color,
                          /minoru/points2,
                          /diagnostics,
                          #Xiroi
                          /xiroi/nav_sts,
                          /xiroi/joy,
                          /xiroi/odometry/filtered_map,
                          /xiroi/odometry/filtered_odom,
                          /xiroi/sensors/gps,
                          /xiroi/setpoints,
                          /xiroi/control/ack_ack,
                          /xiroi/control/ack_joy]
                          # /xiroi/safety]

master_sync/sync_services: [/control/load_trajectory,
                            /control/enable_trajectory,
                            /control/disable_trajectory,
                            /control/disable_thrusters,
                            /control/enable_thrusters,
                            /control/limit_thrusters,
                            /control/unlimit_thrusters,
                            /control/enable_keep_position,
                            /control/disable_keep_position,
                            /topic_logger_robot/start_recording,
                            /topic_logger_robot/stop_recording,
                            /lights_on,
                            /lights_off,
                            /laser_on,
                            /laser_off,
                            /sonar_on,
                            /sonar_off,
                            /modem_on,
                            /modem_off,
                            /nav_status/set_ned_origin,
                            /send_trajectory,
                            /receive_trajectory,
                            /control/goto_holonomic,
                            /control/disable_goto,
                            /xiroi/control/abort_mission,
                            /xiroi/control/enable_keep_position,
                            /xiroi/control/disable_keep_position,
                            /xiroi/control/enable_teleoperation,
                            /xiroi/control/disable_teleoperation,
                            /xiroi/control/disable_thrusters,
                            /xiroi/control/enable_thrusters]